### ISSUE TITLE
#[database] implementation for mongodb ssl support

### ISSUE THREAD

**Issue by lemonxah** [SergioBenitez/Rocket#1115]
# Feature Request

## Why i believe this feature is necessary
Using mongodb servers that is not in your local network like for example mongo atlas servers only use ssl connections. I have used the #[database] implementation for mongodb and it works really well while running it on my machine while coding, but for me to be able to go to staging or production with this i will have to use state management instead as the current #[database] implementation doesn't allow for ssl connections

**Comment by jebrosen** [comment]
In general, most `Poolable` implementations should expose support their database engine's respective options in some way - TLS is just one example.

* `mongodb` has https://docs.rs/mongodb/0.3.12/mongodb/struct.ClientOptions.html. -- the ssl feature doesn't seem to be enabled on docs.rs; the source for `with_ssl` and `with_unauthenticated_ssl` is at https://github.com/mongodb-labs/mongo-rust-driver-prototype/blob/master/src/lib.rs#L262
* `postgres` has https://docs.rs/postgres/0.15.2/postgres/enum.TlsMode.html

For instance, we could support the following in `Cargo.toml`:

```toml
[global.databases.mongo]
url = "mongodb://localhost:27017"
ssl = { ca_file="...", verify_peer = true }

[global.databases.pg]
url = "postgres://"
tls = { mode="prefer", backend="openssl" }
```

I think it's inevitable that these additional options will all be database-specific.

It's also worth noting that the set of supported database crates and versions may change depending on how things go with #1065.
