### ISSUE TITLE
error[E0658]: `macro` is experimental

### ISSUE THREAD

**Issue by songroom2016** [SergioBenitez/Rocket#1134]
the code is same as the example:
```
#![feature(proc_macro_hygiene)]

#[macro_use] extern crate rocket;

#[get("/<name>/<age>")]
fn hello(name: String, age: u8) -> String {
    format!("Hello, {} year old named {}!", age, name)
}

fn main() {
    rocket::ignite().mount("/hello", routes![hello]).launch();
}
```
but my atom ide output is :

error[E0658]: `macro` is experimental
 --> src\main.rs:5:1

  |
5 | #[get("/<name>/<age>")]
  | ^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: for more information, see https://github.com/rust-lang/rust/issues/39412
  = help: add `#![feature(decl_macro)]` to the crate attributes to enable
 
error: aborting due to previous error
 
For more information about this error, try `rustc --explain E0658`.
-----------
D:\rust_plot>rustc  --version
rustc 1.39.0-nightly (eb48d6bde 2019-09-12)

--------
`[dependencies]
rocket = "0.4.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
#hdf5 = "0.5"
rocket_contrib = { path = "D:/Rocket-master/Rocket-master/contrib/lib"}`

-------
win10.

**Comment by jebrosen** [comment]
Are you looking at examples for the `master` branch but using rocket `0.4` in your application? THe 0.4 examples are here: https://github.com/SergioBenitez/Rocket/tree/v0.4/examples

**Comment by songroom2016** [comment]
thanks

**Comment by auipga** [comment]
If I need the master branch, would there be a way to hide those warnings?

**Comment by auipga** [comment]
When I try to use changes I made [here]() using this method

```toml
# Cargo.toml
[patch.crates-io]
rocket = { path = "../../github/Rocket/core/lib" }
rocket_db_pools = { path = "../../github/Rocket/contrib/db_pools/lib" }
rocket_dyn_templates = { path = "../../github/Rocket/contrib/dyn_templates" }
```
then I get the same `warning: macro is experimental` 12 times.
This makes me think, that it still is in issue _somehow_. (I'm now to Rust, please let me know what my mistake in thinking is here)

---
When I switch to 
```toml
# Cargo.toml
[patch.crates-io]
rocket = { git = 'https://github.com/auipga/Rocket-sqlx-0.7.git', branch = 'sqlx-0.7-update' }
rocket_db_pools = { git = 'https://github.com/auipga/Rocket-sqlx-0.7.git', branch = 'sqlx-0.7-update' }
rocket_dyn_templates = { git = 'https://github.com/auipga/Rocket-sqlx-0.7.git', branch = 'sqlx-0.7-update' }
```
then those warnings are gone. (If I had tried this earlier, I wouldn't have bothered you.)
