### ISSUE TITLE
Question: What is the idiomatic way of storing jsonb in postgres?

### ISSUE THREAD

**Issue by rbjorklin** [SergioBenitez/Rocket#1220]
I'm new to Rust and I'm struggling to figure out a good way of converting my data from the parameter `Json<User>` to something that my database connector will accept. The code below works but makes me cringe. What's a better way of doing this?

```toml
[dependencies]
rocket = "0.4.2"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

[dependencies.rocket_contrib]
default-features = false
version = "0.4.2"
features = ["json", "postgres_pool"]

[dependencies.postgres-types]
default-features = false
version = "0.1"
features = ["derive"]

[dependencies.postgres]
default-features = false
version = "0.15.2"
features = ["with-serde_json"]
```
```rust
#[derive(Serialize, Deserialize, Debug)]
struct User {
    username: String,
    email: String,
    age: u32,
    banned: bool,
}

#[post("/user", format = "application/json", data = "<user>")]
fn post_user(user: Json<User>, db: PostgresDbConn) -> JsonValue {
    let blob = json!({
        "username": user.username,
        "email": user.email,
        "age": user.age,
        "banned": user.banned,
    });
    let blob2: Value = JsonValue::into(blob);
    let id: i64 = db
        .query(
            "INSERT INTO users (blob) VALUES ($1) RETURNING id;",
            &[&blob2],
        )
        .unwrap()
        .get(0)
        .get(0);
    json!({ "id": id })
}
```
