### ISSUE TITLE
Image is not displaying

### ISSUE THREAD

**Issue by hyousef-rusty** [SergioBenitez/Rocket#1292]
I've the below code at my Win10 laptop:
```rust
use rocket_contrib::serve::StaticFiles;

fn main() {
        rocket::ignite()
        .mount("/static",
           StaticFiles::from(concat!(env!("CARGO_MANIFEST_DIR"), "/static")))
       .launch();
}
```

With `static/index.html` as:
```html5
<html><body>
  <h1>Hello, World!</h1>
  <img src='https://www.w3schools.com/images/lamp.jpg' alt='Lamp' width='32' height='32'/>

  <img src='C:\\photos\\lamp.jpg' alt='Lamp' width='32' height='32'/>

  <img src='lamp.jpg' alt='Lamp' width='32' height='32'/>

  </body></html>
```
And `Cargo.html` as:
```toml
[package]
name = "wv"
version = "0.1.0"
authors = ["Hasan Yousef"]
edition = "2018"

[dependencies]
rocket = "0.4.4"
rocket_contrib = "0.4.4"
```

But getting the output as below
![image](https://user-images.githubusercontent.com/60115476/80533880-f965db80-89a6-11ea-8422-a3553da24a72.png)
