### ISSUE TITLE
error[E0463]: can't find crate for `rocket`

### ISSUE THREAD

**Issue by isaacdarcilla** [SergioBenitez/Rocket#1310]
Compiling bootstrap v0.1.0 (/home/marga/Desktop/Dev/Rust/bootstrap)
error[E0463]: can't find crate for `rocket`
 --> src/main.rs:3:14
  |
3 | #[macro_use] extern crate rocket;
  |              ^^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: could not compile `bootstrap`.

To learn more, run the command again with --verbose.

**Comment by isaacdarcilla** [comment]
[package]
name = "bootstrap"
version = "0.1.0"
authors = ["isaacdarcilla <isaacdarcilla@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.rocket_contrib]
rocket = "0.4.4"
default-features = false
features = ["handlebars_templates", "tera_templates"]

**Comment by isaacdarcilla** [comment]
```toml
[package]
name = "bootstrap"
version = "0.1.0"
authors = ["isaacdarcilla <isaacdarcilla@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.rocket_contrib]
rocket = "0.4.4"
default-features = false
features = ["handlebars_templates", "tera_templates"]```


Here's the Cargo.toml

**Comment by isaacdarcilla** [comment]
> @isaacdarcilla Can you show your Cargo.toml please?

https://github.com/isaacdarcilla/sbadmin2-rust

**Comment by olback** [comment]
Your dependency section should look something like this:
```toml
[dependencies]
rocket = "0.4.4"
rocket_contrib = { version = "0.4.4", default-features = false, features = [ "handlebars_templates",  "tera_templates" ] }
```
alternatively
```toml
[dependencies]
rocket = "0.4.4"

[dependencies.rocket_contrib]
version = "0.4.4"
default-features = false
features = ["handlebars_templates", "tera_templates"]
``` 

rocket and rocket_contrib are two diffrent crates, rocket contains the core and rocket_contrib contains nice to haves like templateing and JSON responders.
