### ISSUE TITLE
StaticFiles in production mode.

### ISSUE THREAD

**Issue by Darkkaiserl** [SergioBenitez/Rocket#1339]
StaticFiles is not supported in production mode?...

I use StaticFiles in dev and it´s all fine, but in prod mode don´t exist one file.

nightly-x86_64-pc-windows-msvc unchanged - rustc 1.45.0-nightly

Cargo.toml
``` toml
[dependencies.rocket]
version = "0.4.5"
default-features = false
features = ["tls"]

[dependencies.rocket_contrib]
version = "0.4.5"
default-features = false
features = ["tera_templates", "serve", "helmet", "diesel_mysql_pool", "json"]
```

main.rs
``` rust
#![feature(proc_macro_hygiene, decl_macro)]
#[macro_use] extern crate rocket;
#[macro_use] extern crate rocket_contrib;
#[macro_use] extern crate diesel;
#[macro_use] extern crate serde_derive;

use rocket_contrib::helmet::{SpaceHelmet, Hsts};
use rocket::request::{self, Request, FromRequest, Form};
use rocket_contrib::serve::{StaticFiles};
use rocket_contrib::templates::{Template};

use rocket::response::Redirect;
use rocket::http::Status;
use rocket::Outcome;

use std::collections::HashMap;

pub mod get;
pub mod post;
pub mod cors;
pub mod models;
pub mod schema;

#[database("base")]
pub struct MySQL(diesel::MysqlConnection);

pub type Session<'a> = rocket_session::Session<'a, HashMap<&'static str, String>>;

fn main() {
    rocket::ignite()
    .register(catchers![err_catch::n_found404])
    .mount("/", routes![get::index, get::logout])
    .mount("/", routes![post::f1, post::f2, post::f3, post::f4])
    .mount("/", StaticFiles::from("static"))
    .attach(SpaceHelmet::default().enable(Hsts::default()))
    .attach(Template::fairing())
    .attach(Session::fairing())
    .attach(MySQL::fairing())
    .attach(cors::CorsFairing)
    .launch();
}
```

Thx so much.
