### ISSUE TITLE
.env DATABASE_URL with docker-compose host error

### ISSUE THREAD

**Issue by ycvbcvfu** [SergioBenitez/Rocket#1382]
Hi, I have a problem with docker(docker-compose), at `.env`

`docker-compose file about mysql `

```
version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - ./compose/local/mysql/mycustom.cnf:/etc/mysql/conf.d/custom.cnf
    env_file:
      - ./.envs/.local/.mysql
```

`./.envs/.local/.mysql`

```
MYSQL_HOST=db
MYSQL_ROOT_PASSWORD=root
MYSQL_USER=username
MYSQL_PASSWORD=password
MYSQL_DATABASE=blog
```

`.env`

```
DATABASE_URL=mysql://username:password@db:3306/blog
```

and  `config.rs` 

```

/// Create rocket config from environment variables
pub fn from_env() -> Config {
    let environment = Environment::active().expect("No environment found");

    let port = env::var("PORT")
        .unwrap_or_else(|_| "8000".to_string())
        .parse::<u16>()
        .expect("PORT environment variable should parse to an integer");


    let mut database_config = HashMap::new();
    let mut databases = HashMap::new();
    let database_url =
        env::var("DATABASE_URL").expect("No DATABASE_URL environment variable found");
    database_config.insert("url", Value::from(database_url));
    databases.insert("diesel_mysql_pool", Value::from(database_config));

    Config::build(environment)
        .environment(environment)
        .port(port)
        .extra("databases", databases)
        .finalize()
        .unwrap()
}
```

When i run the program(docker-compose up)，get the errors

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ConnectionError(BadConnection("Can\'t connect to MySQL server on \'db\' (115)"))', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/diesel_cli-1.4.1/src/main.rs:83:13
```

BTW, there is no problem when I change the local variable(not use docker)
