### ISSUE TITLE
rocket_contrib::database does not generate Deref for type

### ISSUE THREAD

**Issue by jl-a** [SergioBenitez/Rocket#1436]
**Rocket version**: 0.5.0-dev from Github

**rustc version**: 1.46.0

**Operating System**: Manjaro Linux 20.1, kernel 5.8.6-1

**Description:**

I created a database connection from the [async docs](https://api.rocket.rs/async/rocket_contrib/databases/index.html) for diesel_postgres_pool (also tried for postgres_pool).

```rust
#[database("postgres_conn")]
pub struct Db( diesel::PgConnection );
```

When attempting to dereference my database struct and access the inner connection type, the compiler threw the error:

> `type 'Db' cannot be dereferenced`.

The particular code that threw the error:

```rust
let atlases = match atlas_pages::table
    .select( ( ... ) )
    .filter( ... )
    .load::<atlas::Summary>( &*conn ) // error at &*conn
{
    Ok( a )  => a,
    Err( _ ) => Vec::new(),
}
```

The docs indicated that a `Deref` implementation would be automatically generated for the Db type, but it appears that it has not. I tried for both diesel_postgres_pool and postgres_pool, and the error appeared in both cases.

**Further details**

Following are relevant bits and bobs to trace the code flow.

Cargo.toml:

```toml
[dependencies]
rocket = { git = "https://github.com/SergioBenitez/Rocket" }
[dependencies.rocket_contrib]
git = "https://github.com/SergioBenitez/Rocket"
default-features = false
features = ["diesel_postgres_pool"]
```

Rocket.toml

```toml
[ global.databases ]
postgres_conn = { url = "..." }
```

main.rs

```rust
mod atlas;
...
#[macro_use]
extern crate rocket;
#[macro_use]
extern crate rocket_contrib;
#[macro_use]
extern crate diesel;

use rocket::http::CookieJar;
...
pub mod schema;

#[database("postgres_conn")]
pub struct Db( diesel::PgConnection );
...
#[post("/atlas.list")]
async fn atlas_list( conn: Db, cookies: &CookieJar<'_> ) -> ResponseJson {
    atlas::list( conn, cookies ).await
}
...
#[launch]
fn rocket() -> rocket::Rocket {
    rocket::ignite()
    .mount( "/", routes![
        atlas_list
    ] )
    .attach( Db::fairing() )
}
```

atlas.rs
```rust
use crate::atlas;
use crate::Db;
use rocket_contrib::databases::diesel::{ self, prelude::* };
...
pub async fn list( conn: Db, cookies: &CookieJar<'_> ) -> ResponseJson {
    use crate::schema::atlas_pages;
    let atlases = match atlas_pages::table
        .select( (
            atlas_pages::atlas_id,
            atlas_pages::title,
            atlas_pages::image,
         ) )
        .order( atlas_pages::title.desc() )
        .filter( atlas_pages::page_id.eq( "index" ) )
        .load::<atlas::Summary>( &*conn ) // Error here
    {
        Ok( a )  => a,
        Err( _ ) => Vec::new(),
    };
...
```
