### ISSUE TITLE
Add sticky sidebar to rocket.rs guides

### ISSUE THREAD

**Issue by charrondev** [SergioBenitez/Rocket#1485]
It can be pretty easy to lose the sidebar while passing through rocket guides.

A lot of docs today have a sticky sidebar that helps keep the table of contents in place as you read your doc.

## Examples

|Site|Image|
|---|---|
|Rust Books|![image](https://user-images.githubusercontent.com/1770056/100532944-cdc10300-31cc-11eb-8434-d7cd586a9b6b.png)|
|Cargo Docs|![image](https://user-images.githubusercontent.com/1770056/100533011-9ef75c80-31cd-11eb-8535-4837dae31e5d.png)|
|rocket.rs (with this extra CSS)|![2020-11-28 23 01 48](https://user-images.githubusercontent.com/1770056/100533049-00b7c680-31ce-11eb-9fd7-40a7ea94dce0.gif)|

## Applying to rocket.rs

It's only 6 lines of CSS

```css
#sidebar nav {
    position: sticky;
    top: 0;
    max-height: 100vh;
    overflow: auto;
}
```

Additionally if you want to wide/visible scrollbars (as is common in rust books, & cargo docs, as well as the Rocket API docs), it's just a few more lines of CSS

```css
html, body {
  background-color: #272727;
}

::-webkit-scrollbar {
    width: 12px;
}

::-webkit-scrollbar-thumb {
    background-color: rgba(255, 255, 255, 0.2);
}
```

I'd make a PR but I can't seem to find where the stylesheet for the site is (it doesn't seem to be in this repo).
