### ISSUE TITLE
Rocket MongoDB Compatibility issue -  failed to select a version for `ring`.

### ISSUE THREAD

**Issue by jdaruja** [SergioBenitez/Rocket#1493]
I have googled for the solution Rocket MongoDB Compatibility issue but as per ticket 975 it looks closed.

I am using latest version still i get the error.

error: failed to select a version for `ring`.
    ... required by package `rustls v0.17.0`
    ... which is depended on by `mongodb v1.1.1`
    ... which is depended on by `api_service v0.1.0 (/home/justin/Project/Rust lang/rustApi)`
versions that meet the requirements `^0.16.11` are: 0.16.19, 0.16.18, 0.16.17, 0.16.16, 0.16.15, 0.16.14, 0.16.13, 0.16.12, 0.16.11

the package `ring` links to the native library `ring-asm`, but it conflicts with a previous package which links to `ring-asm` as well:
package `ring v0.13.5`
    ... which is depended on by `rustls v0.14.0`
    ... which is depended on by `hyper-sync-rustls v0.3.0-rc.4`
    ... which is depended on by `rocket_http v0.4.6`
    ... which is depended on by `rocket v0.4.6`
    ... which is depended on by `api_service v0.1.0 (/home/justin/Project/Rust lang/rustApi)`

failed to select a version for `ring` which could resolve this conflict

Here is my depend ices

[dependencies]
clap = "3.0.0-beta.2"
config = "0.10.1"
openssl = "0.10.30"
rocket = { version = "0.4.6", features = ["tls"] }
rocket_contrib = "0.4.6"
#rocket = {git = "https://github.com/SergioBenitez/Rocket.git", features = ["tls"]}
#rocket_contrib = { features = ["uuid"], git = "https://github.com/SergioBenitez/Rocket.git" }
#rocket_codegen = { git = "https://github.com/SergioBenitez/Rocket.git" }
serde = { version = "1.0.116", features = ["derive"] }
#tokio = { version = "0.2.24", features = ["macros", "rt-threaded"] }
thiserror = "1.0"
chrono = { version = "0.4", features = ["serde"] }
futures = { version = "0.3.4", default-features = false, features = ["async-await"] }
hmac = "0.10.1"
sha2 = "0.9.2"
base64 = "0.13.0"
hex = "0.4.0"
mongodb = "1.1.1"
warp = "0.2"

Please suggest me a solution

**Comment by ericpan64** [comment]
Not an expert, though does your project really need to list that many dependencies? Rather than a Rocket issue, this seems like an issue where Cargo is trying to respect all of the listed versions and it's running into some conflict between libraries

I'm currently working on a Rocket/MongoDB project and my dependencies build fine. I'm using rocket version 0.4.5 thought if I had to guess I don't think it makes that much of a difference.

Our use-cases are very likely different, though if it helps as a reference here's my Cargo.toml:
```toml
[dependencies]
rocket = "0.4.5"
uuid = { version = "0.8", features = ["v4"] }
mongodb = { version = "1.1.1", default-features = false, features = ["sync"]}
blake2 = "0.9.1"
hex = "0.3.1"
serde = "1.0.118"
jsonwebtoken = "7.2.0"
chrono = "0.4.19"

# Docs: https://api.rocket.rs/v0.4/rocket_contrib/
[dependencies.rocket_contrib]
version = "0.4.5"
default-features = false
features = ["handlebars_templates", "tera_templates"]
```
