### ISSUE TITLE
Warning: found value for deprecated config key log

### ISSUE THREAD

**Issue by mvolkmann** [SergioBenitez/Rocket#1519]
I am getting "Warning: found value for deprecated config key `log`" when I run an app that uses Rocket that is built with `cargo build --release`.

Here are my dependencies:

```toml
rocket = { git = "https://github.com/SergioBenitez/Rocket", branch = "master" }
rocket_contrib = { git = "https://github.com/SergioBenitez/Rocket", branch = "master", features = ["json"] }
serde = { version = "1.0.118", features = ["derive", "rc"] }
serde_json = "1.0.60"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
```

I am running macOS 11.1.

Here is my Rocket.toml file:

```toml
[debug]
address = "127.0.0.1"
port = 1234
log = "normal"

[staging]
address = "0.0.0.0"
port = 1234
log = "normal"

[release]
address = "0.0.0.0"
port = 1234
log = "critical"
```

My code is in the repo here: https://github.com/mvolkmann/rust-rocket-demo
