### ISSUE TITLE
rocket_contrib::uuid::Uuid wrong error return type

### ISSUE THREAD

**Issue by Roms1383** [SergioBenitez/Rocket#1565]
Hello everybody !

This morning I tried to switch from rocket `0.4.7` to the master `0.5.0-dev` and ended up on an issue related to `rocket_contrib::uuid::Uuid`.

## Bug Reports

bug happens on `cargo build` for this version :

- rustup version : `rustup 1.23.1 (3df2264a9 2020-11-30)`
- rustc version : tested on both `rustc 1.52.0-nightly (234781afe 2021-03-07)` and `rustc 1.50.0 (cb75ad5db 2021-02-10)`
- rocket version : master [#f4548950](https://github.com/SergioBenitez/Rocket#f4548950)

<img width="1021" alt="Screen Shot 2021-03-08 at 10 08 01" src="https://user-images.githubusercontent.com/21016014/110270014-7f0adc80-7ff7-11eb-8eb6-32b6520d2378.png">

## Questions

Is there any commit SHA which could be considered as somehow stable while waiting for `0.5.0` release ?

## General Comments

Just a big thanks for this crate, it is awesome !

**Comment by Roms1383** [comment]
As additional context, here's a sample from my `Cargo.toml` :
```toml
[dependencies]
# ...
rocket = { git = "https://github.com/SergioBenitez/Rocket" }
# ...
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
# ...
uuid = { version = "0.8", features = ["serde", "v4"] }

[dependencies.rocket_contrib]
git = "https://github.com/SergioBenitez/Rocket"
default-features = false
features = ["json", "uuid", "diesel_postgres_pool"]
```

**Comment by Roms1383** [comment]
Well, in the meantime I ran a `rustup update` and set `rustup override set stable`.

After a `cargo clean` and a few changes to be compatible with `0.5.0-dev`,
I got it working mainly by sticking (at least for now) to bare [`uuid::Uuid`](https://docs.rs/uuid/0.8.2/uuid/).

Here's my updated `Cargo.toml` :
```toml
[dependencies]
rocket = { git = "https://github.com/SergioBenitez/Rocket" }
# ...
uuid = { version = "0.8", features = ["serde", "v4"] }

[dependencies.rocket_contrib]
git = "https://github.com/SergioBenitez/Rocket"
default-features = false
features = ["json", "diesel_postgres_pool"]
```

I made an attempt at switching to `rocket_contrib::uuid::Uuid` afterwards and it seems possible but in my case with quite a lot of refactoring.

Feel free to close this issue if nobody runs into it.
