### ISSUE TITLE
How to set concurrent request processing

### ISSUE THREAD

**Issue by lunemec** [SergioBenitez/Rocket#161]
I created simple HTTP service:
https://github.com/lunemec/rust-birkana-http

Just to try HTTP frameworks in rust. It performs OK, but can't handle concurrent requests. This can be seen on serving static files - when you open dev/release version in 2 browsers and load them at the same time, one of them waits for the other to finish loading resources. 

I saw mention in #21 that there is some `workers` setting? I couldn't find any mention of it in the API docs or googling it. Does rocket have this option or is it up to me to create ThreadPool and somehow tie it into http serving?

Thank you.

**Comment by SergioBenitez** [comment]
In version 0.1, Rocket sets the number of threads to be the number of cores on the machine. The number of threads cannot be changed. Presumably your machine has a single core. 

In the soon to be released v0.2, Rocket sets the default number of threads to be `max(2, CPU cores)`. The number can be changed via the `workers` configuration parameter. I'm hoping to release v0.2 in a few days, and certainly by the end of the week.

**Comment by lunemec** [comment]
Thank you for the answer,
I'm using version 0.1.5, but my machine is Macbook Pro (Retina 13-inch, Early 2015), which has Core i5 dual core with hyper-threading. So 4 logical cores. I wonder if there is some shenanigans with FS locking the files being read .. ? You can easily clone the repo I posted and run it to see the result of the concurrent access...

**Comment by SergioBenitez** [comment]
I tried this out on my machine, and Rocket is properly serving requests from multiple workers.

Perhaps you can try to see how many works Rocket is using my temporarily switching to the master branch? Just change your `Cargo.toml` to:

```toml
[package]
name = "rust-birkana-http"
version = "0.1.0"
authors = ["Nemec Lukas <lukas.nemec2@firma.seznam.cz>"]

[dependencies]
rocket = { git = "https://github.com/SergioBenitez/Rocket" }
rocket_codegen = { git = "https://github.com/SergioBenitez/Rocket" }
rust-birkana = "1.1.1"
serde = "0.8"
serde_derive = "0.8"

[dependencies.rocket_contrib]
git = "https://github.com/SergioBenitez/Rocket"
default-features = false
features = ["tera_templates"]
```
