### ISSUE TITLE
Template question: how to use a static string template

### ISSUE THREAD

**Issue by mcastorina** [SergioBenitez/Rocket#1637]
How do you use a static string template instead of a file? An example would be really helpful.

1. The version of Rocket this question is based on, if any.
```
version = "0.4.7"
```

2. What steps you've taken to answer the question yourself.

I found documentation on using `Template::custom()`. I tried the below code which compiles but gets an error when trying to render the template: `Template 'signup' does not exist.`

```rust
rocket::ignite()
    .attach(Template::custom(|engines| {
        engines
            .handlebars
            .register_template_string("signup", include_str!("../html/signup.hbs"))
            .expect("Failed registering template")
    }))
```

My Cargo.toml has the handlebars feature as well.

```toml
[dependencies.rocket_contrib]
version = "0.4"
default-features = false
features = ["handlebars_templates"]
```

3. What documentation you believe should include an answer to this question.

Either documentation with `Template::custom` or an example using `handlebars.register_template_string`.
