### ISSUE TITLE
Debug assertion panics due to invalid URIs from upstream Hyper

### ISSUE THREAD

**Issue by ZoeyR** [SergioBenitez/Rocket#1831]
**Description**

Using any rocket server I attempted to visit a url with `[` in the path. I get a "Connection Reset" error in my browser and the rocket log fills with the following:
```
thread 'rocket-worker-thread' panicked at 'assertion failed: Origin::parse(uri.as_str()).is_ok()', C:\Users\zoey\.cargo\git\checkouts\rocket-8bf16d9ca7e90bdc\786db9b\core\lib\src\request\request.rs:978:9
```

**To Reproduce**
```rust
// main.rs
#[macro_use] extern crate rocket;

#[get("/hello/<name>/<age>")]
fn hello(name: &str, age: u8) -> String {
    format!("Hello, {} year old named {}!", age, name)
}

#[launch]
fn rocket() -> _ {
    rocket::build().mount("/", routes![hello])
}
```

```toml
# Cargo.toml
[package]
name = "rocket_panic_test"
version = "0.1.0"
edition = "2018"

[dependencies]
rocket = { git = "https://github.com/SergioBenitez/Rocket", branch = "master" }
```

Visit `http://localhost:8000/[`

**Expected Behavior**

Rocket returns a 404 since the route does not exist.

**Environment:**

 - OS Distribution and Kernel: Windows 10
 - Rocket Version: master@786db9b

**Additional Context**

This came up due to a malformed js `fetch` that accidentally requested `http://localhost:8000/[object%20Object]`. I reduced the url to the part that causes the panic.
