### ISSUE TITLE
`asynchronous::LocalResponse.into_json::<T>() hangs indefinitely

### ISSUE THREAD

**Issue by veeg** [SergioBenitez/Rocket#1893]
**Description**

Invoking [`rocket::local::asynchronous::LocalResponse.into_json::<T>().await`](https://api.rocket.rs/v0.5-rc/rocket/local/asynchronous/struct.LocalResponse.html#method.into_json) hangs indefinitely.

**To Reproduce**
```toml
[package]
name = "rocket-into-json"
version = "0.1.0"
edition = "2018"

[dependencies]
rocket = { version = "0.5.0-rc.1", features = ["json"] }
serde = "1"
tokio = { version = "1", features = ["full"] }
```

```rust
use rocket::{get, http::Status, local::asynchronous::Client, routes, serde::json::Json};
use serde::{Deserialize, Serialize};

#[derive(Debug, Deserialize, Serialize)]
struct Hello {
    hello: String,
}

#[get("/")]
fn hello_world() -> Json<Hello> {
    Json(Hello {
        hello: "world".to_string(),
    })
}

#[tokio::main]
async fn main() {
    let rocket = rocket::build().mount("/", routes![hello_world]);
    let client = Client::untracked(rocket).await.expect("test client");

    let response = client.get("/").dispatch().await;
    assert_eq!(response.status(), Status::Ok);

    let wire = response
        .into_json::<Hello>()
        .await
        .expect("deserializing success response");
    assert_eq!(wire.hello, "world".to_string());
}
```

**Expected Behavior**
The program shall terminate successfully.

**Environment:**

 - OS Distribution and Kernel: Ubuntu 20.04.3 LTS, Linux 5.4.0
 - Rocket Version: [0.5.0-rc.1
