### ISSUE TITLE
JSON response: Responder<'_, '_>` is not satisfied

### ISSUE THREAD

**Issue by ynhhoJ** [SergioBenitez/Rocket#1932]
**Description**
JSON example doesn't work. Always give error on compilation.
Example: https://github.com/SergioBenitez/Rocket/blob/v0.4/examples/json/src/main.rs

**To Reproduce**

How to reproduce the bug. A fully working code example (`main.rs` + `Cargo.toml`) is preferred.
```rs
// main.rs
#[macro_use] extern crate rocket;
use serde::Serialize;
use rocket_contrib::json::Json;

// #[derive(Debug, Deserealize, Serialize)] -- doesn't work
#[derive(Serialize)]
struct User {
    name: String,
    age: u8,
    alive: bool,
}

#[get("/")]
fn index() -> &'static str {
    "Hello, world!"
}

#[get("/user")]
fn login() -> Json<User> {
    Json(User {
        name: "Jon Snow".to_string(),
        age: 21,
        alive: true,
    })
}

#[rocket::main]
#[allow(unused_must_use)]
async fn main() {
    rocket::build()
        .mount("/", routes![index, login])
        .launch()
        .await;
}
```

```toml
# cargo.toml
[package]
name = "blog-back-end"
version = "0.0.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dependencies.rocket_contrib]
version = "0.4.10"
default-features = false
features = ["json"]
```

**Expected Behavior**
I expect it will possible to send JSON as response.

**Environment:**

 - OS Distribution and Kernel: Windows 19043.1237
 - Rocket Version: 0.5.0-rc.1
 - rustc 1.57.0-nightly (f03eb6bef 2021-10-02)

**Additional Context**

```
error[E0277]: the trait bound `rocket_contrib::json::Json<User>: Responder<'_, '_>` is not satisfied
   --> src\main.rs:18:15
    |
18  | fn login() -> Json<User> {
    |               ^^^^^^^^^^ the trait `Responder<'_, '_>` is not implemented for `rocket_contrib::json::Json<User>`
    |
note: required by `route::handler::<impl Outcome<rocket::Response<'o>, Status, rocket::Data<'o>>>::from`
   --> C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\rocket-0.5.0-rc.1\src\route\handler.rs:188:5
    |
188 |     pub fn from<R: Responder<'r, 'o>>(req: &'r Request<'_>, responder: R) -> Outcome<'r> {
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
I know, it's not stackoverflow, but, what i'm doing wrong?

**Comment by ELD** [comment]
You're mixing the Rocket v0.4 example with Rocket 0.5 code. JSON support was promoted directly into Rocket 0.5 via a Cargo feature.

This is the example you're going to want to follow for Rocket 0.5: https://github.com/SergioBenitez/Rocket/blob/v0.5-rc/examples/serialization/src/json.rs

**Comment by ynhhoJ** [comment]
@ELD , thank you for help!

```rs
// main.rs
#[macro_use] extern crate rocket;
use rocket::serde::json::{json, Value};
use rocket::serde::{Serialize, Deserialize};

#[derive(Serialize, Deserialize)]
#[serde(crate = "rocket::serde")]
struct User {
    name: String,
    age: u8,
    alive: bool,
}

#[get("/")]
fn index() -> &'static str {
    "Hello, world!"
}

#[get("/user")]
fn login() -> Value {
    json!(User {
        name: "Jon Snow".to_string(),
        age: 21,
        alive: true,
    })
}

#[rocket::main]
#[allow(unused_must_use)]
async fn main() {
    rocket::build()
        .mount("/", routes![index, login])
        .launch()
        .await;
}
```

```toml
[package]
name = "blog-back-end"
version = "0.0.1"
edition = "2018"

[dependencies.rocket]
version = "0.5.0-rc.1"
features = ["json"]
```
