### ISSUE TITLE
Hit unreachable code

### ISSUE THREAD

**Issue by NilsIrl** [SergioBenitez/Rocket#1977]
**Description**

I hit the following line which should be unreachable:

https://github.com/SergioBenitez/Rocket/blob/8cae077ba1d54b92cdef3e171a730b819d5eeb8e/contrib/sync_db_pools/lib/src/connection.rs#L58

This occurs only on some of the runs. Seemingly at random.

**To Reproduce**

```rs
use rocket::{figment::util::map, Build, Config};
use rocket_sync_db_pools::{database, diesel};

#[database("monitors")]
struct MonitorsDbConn(diesel::PgConnection);

fn rocket() -> rocket::Rocket<Build> {
    rocket::custom(Config::figment().merge((
        "databases",
        map![
                "monitors" => map!{
                    "url" => "postgres://localhost/monitors"
                }
        ],
    )))
    .attach(MonitorsDbConn::fairing())
}

#[rocket::main]
async fn main() {
    tokio::task::spawn(async { rocket().ignite().await?.launch().await });
}
```

Cargo.toml:

```toml
[package]
name = "monitors"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc.1"
tokio = "1.13.0"
rocket_sync_db_pools = { version = "0.1.0-rc.1", default-features = false, features = [ "diesel_postgres_pool" ] }
```

**Environment:**

 - OS Distribution and Kernel: macOS 11.6 M1
 - Rocket Version: 0.5.0-rc.1
