### ISSUE TITLE
rocket-worker-thread panics whith PoisonError after recieving Os Error { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" } once

### ISSUE THREAD

**Issue by FrankenApps** [SergioBenitez/Rocket#2031]
**Description**

I have a simple rocket application running on a server and it receives around 150 requests per day. After a week or two the service stops working until I restart it.

This is the output from `stderr`:
```
thread 'rocket-worker-thread' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.6.1/src/runtime/blocking/pool.rs:261:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'rocket-worker-thread' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.6.1/src/runtime/blocking/pool.rs:287:86
thread 'rocket-worker-thread' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.6.1/src/runtime/blocking/pool.rs:287:86
...
thread 'rocket-worker-thread' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.6.1/src/runtime/blocking/pool.rs:287:86
thread 'rocket-worker-thread' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.6.1/src/runtime/blocking/pool.rs:261:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'rocket-worker-thread' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.6.1/src/runtime/blocking/pool.rs:287:86
thread 'rocket-worker-thread' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.6.1/src/runtime/blocking/pool.rs:287:86
...
thread 'rocket-worker-thread' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.6.1/src/runtime/blocking/pool.rs:287:86
```

I restarted the server after the first panic and then it ran fine for about two weeks before crashing again, which I have now observed multiple times (two cycles are shown in the log).

I am sorry that I do not have more information (I am working to collect those though) but I thought the problem was significant enough to post it as is.

**Expected Behavior**

I expect rocket to safely recover from the panic and not to get tangled up because of poised threads.

**Environment:**

 - OS Distribution and Kernel: Ubuntu 20.04
 - Rocket Version: 0.5.0-rc.1

**Additional Context**
As I currently see this Issue, the problem is basically that the socket [Would Block](https://sockettools.com/kb/operation-would-block-error/) and while this certainly is not a fatal error, it seems to me as if it is not handled correctly.

I guess it is worth noting, that in the application referred to above I use some other dependencies, namely:
```toml
base64 = "0.13.0"
genpdf = { version = "0.2.0", features = ["images"] }
image = "0.23.14"
imageproc = "0.22.0"
lettre = { version = "0.10.0-rc.3", default-features = false, features = ["sendmail-transport", "native-tls", "hostname", "r2d2", "builder"] }
mysql_async = "0.28.0"
rocket = { version = "0.5.0-rc.1", features = ["json", "tls"] }
rocket_cors = { git = "https://github.com/lawliet89/rocket_cors", rev = "ad80993bcb420437a2998404bde51da9a9c0b151" }
```
however the only other two dependencies, that I think might be the culprint here are `mysql_async` and `rocket_cors`, but I feel like it is most likely an issue with `rocket`.
