### ISSUE TITLE
Freeze on 0.5-rc

### ISSUE THREAD

**Issue by Stargateur** [SergioBenitez/Rocket#2156]
It's the second time my app freeze, both time the app was running since ~6 weeks

**To Reproduce**

Unable to reproduce easily

**Environment:**

 - Linux optomata 5.16.2-arch1-1 `#1` SMP PREEMPT Thu, 20 Jan 2022 16:18:29 +0000 x86_64 GNU/Linux
 - Docker version 20.10.12, build e91ed5707e

```toml
[profile.release]
opt-level = 2
debug = false
debug-assertions = false
overflow-checks = false
lto = true
panic = 'unwind'
incremental = false
codegen-units = 16
rpath = false

[dependencies.rocket]
version = "0.5.0-rc.1"
features = ["json", "uuid", "tls"]

[dependencies.tokio]
version = "1"
features = ["full"]

[dependencies.deadpool-postgres]
version = "0.9"
default-features = false
features = ["rt_tokio_1"]

[dependencies.tokio-postgres]
version = "0.7"
features = ["runtime", "with-uuid-0_8", "with-chrono-0_4", "with-serde_json-1"]
```

I use TLS, the app is inside a docker. When it's freeze the app is completely unresponsive, not an simple log even in tracing.
 Possibly tokio fault.
