### ISSUE TITLE
one Uuid type to rule them all

### ISSUE THREAD

**Issue by Taiwing** [SergioBenitez/Rocket#2295]
**Existing Functionality**

I am using Rocket to build an api for a small web application. In my database and in my api requests/responses I need Uuids to manage user accounts and data.

Since I must fetch Uuids from postgres I use sqlx's uuid feature. However I also need my Uuids to be serialized and deserialized for handling api requests. For this I use Rocket's uuid feature to get Serde's version of the Uuid type. This means I have two different (but extremely similar) Rust types to handle the same kind of data. This is not ideal especially when I need to use them together.

**Suggested Changes**

I'm wondering if it would be possible for the Rocket library to export a single Uuid type that would implement Serde's Serialize/Deserialize traits and be a valid sqlx db type for sql requests.

**Alternatives Considered**

I created a function that converts one type into the other. This is the simplest solution I could come up with. I tried creating my own Uuid type that would implement the needed traits but I could not get it to work. It also seemed like too much work considering the scope of the project I'm currently working on.

**Comment by blackghost1987** [comment]
Your description seems a bit confusing, for example the part about "Serde's version of the Uuid type" is kinda backwards. Serde doesn't have an Uuid type, Rocket is including the Uuid crate (if the feature is enabled), which has Serde integration as an optional feature, to implement serialize / deserialize.

The Sqlx crate is also using the Uuid crate, so the type re-exported by Rocket and the type re-exported by Sqlx should be from the same crate actually!

It's possible your exact dependencies are instructing the compiler to choose two different versions of the Uuid crate at the same time (which should be only possible if they are not semver compatible). Or maybe the compiler is not smart enough to recognize that these are actually the same type, because of some renaming / versioning issues. 

So the suggested change is not really possible imho, this should already be the case. It's hard to know what's exactly the problem in your project without knowing the exact versions you are using, so please attach your Cargo.toml and maybe even your current Cargo.lock as well!

**Comment by Taiwing** [comment]
Thanks for the reply, I did not know all that. Indeed there seems to be two different Uuid types in my crate. I can't use them interchangeably.

Here is the Cargo.toml file:

```toml
[package]
name = "api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
regex = "1.5.6"
uuid = { version = "1.1.2", features = ["v4"] }
rocket = { version = "0.5.0-rc.2", features = ["secrets", "json", "uuid"] }
sqlx = { version = "0.5", default-features = false, features = ["uuid", "macros"] }
rocket_db_pools = { version = "0.1.0-rc.2", features = ["sqlx_postgres"] }
rust-argon2 = "1.0"
```
