### ISSUE TITLE
Tera inheritance does not seem to work

### ISSUE THREAD

**Issue by bbstilson** [SergioBenitez/Rocket#2482]
**Description**

Tera inheritance requires that the parent template(s) be initialized before dependents. This does not seem to be happening.

```bash
✗ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.07s
     Running `target/debug/rocket_tera`
Error: Failed to initialize Tera templating.
   >> Template 'hello' is inheriting from 'templates/base.html.tera', which doesn't exist or isn't loaded.
   >> Template initialization failed. Aborting launch.
Error: Rocket failed to launch due to failing fairings:
   >> Templating
```

**To Reproduce**

### Cargo.toml

```toml
[package]
name = "rocket_tera"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5.0-rc.2", default-features = false }
rocket_dyn_templates = { version = "0.1.0-rc.2", default-features = false, features = [
  "tera",
] }
```

### Rocket.toml

```toml
[default]
template_dir = "templates"
```

### src/main.rs

```rs
use rocket::{get, launch, routes};
use rocket_dyn_templates::{context, Template};

#[get("/")]
fn hello() -> Template {
    Template::render("hello", context! { hello: "hi" })
}

#[launch]
async fn rocket() -> _ {
    rocket::build()
        .attach(Template::fairing())
        .mount("/hello", routes![hello])
}
```

### templates/hello.html.tera

```html
{% extends "templates/base.html.tera" %}

{% block content %}
<h1>Hi: {{ hello }}</h1>
{% endblock content %}
```

### templates/base.html.tera

```html
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>

<body>
  <div>
    {% block content %}
    {% endblock content %}
  </div>
</body>

</html>
```

**Expected Behavior**

The `hello.html.tera` template should be renderable.

**Environment:**

 - OS Distribution and Kernel: Pop!_OS 22.04
 - Rocket Version: [e.g. 0.5.0-rc2]

```bash
cargo --version
cargo 1.69.0-nightly (17b3d0de0 2023-02-17)
```

**Additional Context**

Really enjoying Rocket so far 🙂
