### ISSUE TITLE
use rocket orm sqlx error

### ISSUE THREAD

**Issue by fate-zx** [SergioBenitez/Rocket#2486]
### Rocket.toml:
```toml
[debug]
port = 9001
## only the `json` key from `default` will be overridden; `form` will remain
limits = { json = "10MiB" }

## set only when compiled in release mode, i.e, `cargo build --release`
## don't use this secret_key! generate your own and keep it private!
[release]
port = 9999
secret_key = "hPRYyVRiMyxpw5sBB1XeCMN1kFsDCqKvBi2QJxBVHQk="
 [default.databases,mysql_logs]
 url = "mysql://root:task123456@127.0.0.1:3306/blog"
```
### How to configure the configuration file？
