### ISSUE TITLE
Memory leak when returning large responses

### ISSUE THREAD

**Issue by Scripter17** [SergioBenitez/Rocket#2521]
**Description**

When returning large responses, RAM usage goes up and doesn't seem to ever go down. Weirdly it seems to plateu after a few requests. The example below maxes out at 28.5 MB of RAM.

**To Reproduce**

main.rs
```Rust
#[macro_use] extern crate rocket;

#[get("/")]
async fn index() -> String {
    format!("{:?}", (1..1000000).collect::<Vec<_>>())
}

#[launch]
fn rocket() -> _ {
    rocket::build()
        .mount("/", routes![index])
}
```
Cargo.toml
```toml
[package]
name = "rocket-leak-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc.3"
```

**Expected Behavior**

RAM usage to spike for a moment as the response is created and sent, then return to pre-request levels

**Environment:**

 - OS Distribution and Kernel: Ubuntu 22.04, Linux kernel 5.19.0-38-generic
 - Rocket Version: 0.5.0-rc.3
