### ISSUE TITLE
Republish rocket_contrib to crates.io to update tera version to 0.10.*

### ISSUE THREAD

**Issue by msarris** [SergioBenitez/Rocket#301]
Hi Sergio,

The published version of rocket_contrib (https://crates.io/crates/rocket_contrib) has a dependency on the tera templating library version 0.7.0 at the moment. I'm trying out some stuff with rocket (great project btw.), and I want to try out some features that are added to tera later (`{% set ... %}` for example). I saw you already updated the version in Cargo.toml in this repo, but probably after it was published?

Would you mind publishing the crate with the latest version? Much appreciated!

Or if you know a way of overriding a version with a newer one (in Cargo.toml), I already tried to use the [replace] section but that only works if the replacement library has the exact same version, that would mean I need to fork the tera repo and just update the version, which seems silly.

Keep up the good work and best regards,

Michali Sarris

**Comment by mp4096** [comment]
Hi, I had a similar question in #300

My solution is to specify dependency on the git repo:

```toml

[dependencies.rocket]
git = "https://github.com/SergioBenitez/Rocket"
rev = "a4292ba666fa60448e575b600d69f131795da080"

[dependencies.rocket_codegen]
git = "https://github.com/SergioBenitez/Rocket"
rev = "a4292ba666fa60448e575b600d69f131795da080"

[dependencies.rocket_contrib]
git = "https://github.com/SergioBenitez/Rocket"
rev = "a4292ba666fa60448e575b600d69f131795da080"
default-features = false
features = ["handlebars_templates"]
```
