### ISSUE TITLE
MongoDB connection pooling leaks connections

### ISSUE THREAD

**Issue by aticu** [SergioBenitez/Rocket#979]
# Bug report

## What is the bug?

When using the MongoDB connection pooling feature, Rocket opens new connections to the MongoDB server on a regular basis (roughly every 11 minutes), leaking the old connections. This happens both in production and development mode. It also happens regardless of any requests being made.

## Version information

Rocket version: 0.4.0
Operating system: Tested on a fresh install of Ubuntu 18.04.1 LTS

### Setup

`Cargo.toml`

```toml
[package]
name = "package"
version = "0.1.0"
authors = ["aticu"]
edition = "2018"

[dependencies]
rocket = "0.4"
rocket_contrib = { version = "0.4", features = ["mongodb_pool"] }
```

`src/main.rs`

```rust
#[rocket_contrib::database("db")]
struct DatabaseConnection(rocket_contrib::databases::mongodb::db::Database);

fn main() {
    rocket::ignite()
        .attach(DatabaseConnection::fairing())
        .launch();
}
```

`Rocket.toml`

```toml
[global.databases]
db = { url = "mongodb://localhost:27017" }
```

### Steps

- Start mongodb and run `cargo run`
- Check the number of open connections with `lsof -p $(pidof package) | grep localhost | grep -v LISTEN | wc -l`
- Wait roughly 11 minutes
- Check the number of connections again: It should have doubled

# Edit

It seems as though there are a lot more open connections than I initially thought. If you use `lsof | grep package | grep localhost | grep -v LISTEN | wc -l` you can see the actual number of open connections opened by the program. Most of those seem to be opened by a thread named `r2d2-work`. This number seems to increase in the same 11 minute interval.
